# Generated by Django 2.0.5 on 2018-06-26 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElevationGeoid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevation', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ElevationMss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevation', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Kmz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='kmz/')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('waterBodyType', models.CharField(max_length=20)),
                ('basin', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('latitude', 'longitude')},
        ),
        migrations.AddField(
            model_name='elevationmss',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addLoc.Location'),
        ),
        migrations.AddField(
            model_name='elevationgeoid',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addLoc.Location'),
        ),
    ]
