# Generated by Django 2.0.5 on 2018-06-27 05:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('addLoc', '0003_auto_20180627_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevationgeoid',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 27, 5, 44, 29, 454641, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
