# Generated by Django 2.0.5 on 2018-06-27 05:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('addLoc', '0004_elevationgeoid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevationmss',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 27, 5, 45, 14, 938092, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
