# Generated by Django 2.0.5 on 2018-06-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addLoc', '0006_auto_20180627_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basin',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='waterbodytype',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
