# Generated by Django 2.0.5 on 2018-06-27 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addLoc', '0008_auto_20180627_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='basin',
        ),
    ]
