# Generated by Django 2.0.5 on 2018-06-27 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addLoc', '0009_remove_location_basin'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='basin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addLoc.Basin'),
        ),
    ]
