# Generated by Django 2.0.5 on 2018-06-27 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addLoc', '0010_location_basin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='basin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addLoc.Basin'),
        ),
    ]
