# Generated by Django 2.0.5 on 2018-06-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addLoc', '0011_auto_20180627_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basin',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='nameLong',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
