# Generated by Django 2.0.5 on 2018-07-02 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addLoc', '0012_auto_20180628_1052'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='elevationgeoid',
            unique_together={('date', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='elevationmss',
            unique_together={('date', 'location')},
        ),
    ]
